# Required to run your project under the correct environment.

language: php

# Versions of PHP you want your project run with.

php:

 - 7.1

before_script:

 - composer self-update

 - composer install --prefer-source --no-interaction --dev

script: php bin/phpunit

language: php

sudo: false

services:
 - mysql

cache:
 directories:
   - $HOME/.composer/cache/files

env:
 - SYMFONY_VERSION="4.3.1" DB=wrk_transport

# Update composer
before-install:
 - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
 - composer install
 - php bin/console doctrine:database:create --env=test
 - php bin/console doctrine:schema:create --env=test
 - php bin/console doctrine:fixtures:load -n --env=test

# Run script
script:
 - php bin/phpunit

# After a build, send email notification with the build results
notifications:
 email: moldwebs@gmail.com


deploy:
  provider: heroku
  app: trnsp
  api_key:
    secure: $HEROKUKEY
